In [1]:
from grasp_pr import read_results, get_filenames

names = get_filenames()
names

['ch150_100_50']

In [2]:
import pandas as pd

path_relinking = pd.concat(
    read_results(name) for name in names
)

In [5]:
path_relinking

,instance,i,p,alpha,best_grasp,best_po,best_diff,po_imps,pr_avg_imps,pr_ls_avg_imps,time_total,time_po,time_po_%,time_pr_avg,time_pr_ls_%_avg
0,ch150_100_50,0,5,2,337,337,0.0,0,0.489474,1.489474,29.497275,22.272299,75.506291,0.117210,62.191857
1,ch150_100_50,0,5,2,337,337,0.0,0,0.742105,1.600000,25.486534,18.284301,71.741027,0.096220,73.743980
2,ch150_100_50,1,5,2,363,363,0.0,0,0.384211,1.226316,36.828771,25.677318,69.720811,0.135132,69.927323
3,ch150_100_50,1,5,2,363,363,0.0,0,0.284211,1.194737,31.591570,20.755548,65.699641,0.109228,75.060779

In [3]:
df_groupby = path_relinking.groupby("instance i p alpha".split(), sort=False)
grouped = df_groupby.mean()
grouped

                        best_grasp  best_po  best_diff  po_imps  pr_avg_imps  \
instance     i p alpha
ch150_100_50 0 5 2           337.0    337.0        0.0      0.0     0.615789
             1 5 2           363.0    363.0        0.0      0.0     0.334211

                        pr_ls_avg_imps  time_total    time_po  time_po_%  \
instance     i p alpha
ch150_100_50 0 5 2            1.544737   27.491905  20.278300  73.623659
             1 5 2            1.210526   34.210170  23.216433  67.710226

                        time_pr_avg  time_pr_ls_%_avg
instance     i p alpha
ch150_100_50 0 5 2         0.106715         67.967918
             1 5 2         0.122180         72.494051